-- ==========================================
-- AI QUIZ GENERATIONS
-- ==========================================

CREATE TABLE IF NOT EXISTS public.ai_quiz_generations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT REFERENCES public.quizzes ON DELETE CASCADE,
  source_files TEXT[] NOT NULL,
  ai_model TEXT NOT NULL,
  requested_count INT NOT NULL,
  generated_count INT NOT NULL,
  generation_duration_ms BIGINT,
  settings JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES public.profiles ON DELETE SET NULL
);

-- RLS
ALTER TABLE public.ai_quiz_generations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can view and manage generations" 
  ON public.ai_quiz_generations FOR ALL 
  USING (public.is_admin(auth.uid()));
